name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd path/to/your/project
          npm install

      - name: Run tests
        run: |
          cd path/to/your/project
          npm test

      - name: Install Cohere CLI
        run: npm install -g cohere-cli

      - name: Send email notification using Cohere API
        run: |
          cohere email send \
            --api-key ${{ secrets.COHERE_API_KEY }} \
            --to 'xyakuzapro@gmail.com' \
            --from 'notifications@os2-openesea.in' \
            --subject 'Test Results' \
            --body 'The tests have completed successfully.'

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: 'mail.os2-openesea.in'
          server_port: 465
          username: 'notifications@os2-openesea.in'
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Test Results'
          body: 'The tests have completed successfully.'
          to: 'xyakuzapro@gmail.com'
          from: 'notifications@os2-openesea.in'

      - name: Send batch emails
        run: ./send_batch_emails.sh